config/routes.rb
Rails.application.routes.draw do

  #get 'users/new'

  resources 'users', only: [:new, :create]

  root 'access#login'

  get 'shopfronts/view'
  get 'shopfronts/cart'
  get 'shopfronts/usermail'
  get 'shopfronts/wishlist'

  get 'admin', to: 'categories#index'
  #get 'access/shop_front'
  #post 'access/shop_front'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :categories

  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  validates :name, uniqueness: { message: "Already exists" }
  validates :name, presence: { message: "Necessary Fields"}
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :category

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :price, presence: { message: "Necessary Fields"}
  validates :price, numericality: { message: "Integer Only"}
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :items
  has_secure_password

  validates :name, :email, :password_digest, :user_type, :contact, :address, presence: { message: "Necessary Fields"}
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    message: "Not Valid Email" }
  validates :email, :contact, uniqueness: { message: "Already exists" }
  validates :contact, numericality: { message: "Integer Only"}
  validates :contact, length: { minimum: 8, maximum: 10, message: "contact no should have 8-10 digits" }
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, except: [:login, :attempt_login, :logout]
  def shop_front
    @categories=Category.all
    @items=Item.all
    @category_id=Category.find(params[:category_id])
    @items=@category.items.all
    render('shop_front')
  end

  def submit_category
    @category=Category.find(params[:category_id])
    @items=@category.items.all
    render('shop_front')
  end

  def login
    if session["email"]
      @user=User.find(session[:email])
      if @user.user_type=="admin"
        redirect_to(categories_path)
      else
        redirect_to(shopfronts_view_path)
      end
    end
  end

  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user=User.where(email: params[:email]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    if authorized_user
      session[:email] = authorized_user.id
      flash[:notice] = "you are now logged in."
      user_type=authorized_user.user_type
      if user_type=="admin"
        redirect_to(categories_path)
      else
        redirect_to(shopfronts_view_path)
      end
    else
      flash.now[:notice] = "Invalid username/password combination"
      render('login')
    end
  end

  def logout
    session[:email] = nil
    session.delete(:cart_item)
    flash[:notice] = 'logged out'
    redirect_to(access_login_path)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def confirm_logged_in
    unless session[:email]
      flash[:notice] = "please log in."
      redirect_to(access_login_path)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :confirm_logged_in
  def index
    @categories=Category.all
    render('index')
  end

  def show
    @category=Category.find(params[:id])
  end

  def new
    @category=Category.new
  end

  def create
    @category=Category.new(category_params)
    if @category.save
      redirect_to(categories_path)
    else
      render('new')
    end
  end

  def edit
    @category=Category.find(params[:id])
  end

  def update
    @category=Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to(categories_path)
    else
      render('edit')
    end
  end

  def delete
    
  end

  def destroy
    @category=Category.find(params[:id])
    @category.destroy
    redirect_to(categories_path)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :confirm_logged_in
  before_action :find_category

  def index
    @items=@category.items.all
    render('index')
  end

  def show
    @item=Item.find(params[:id])
    @categories=Category.all
  end

  def new
    @item=Item.new(category_id: @category.id)
    @categories=Category.all
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to(items_path(category_id: @category.id))
    else
      @categories=Category.all
      render('new')
    end
  end

  def edit
    @item=Item.find(params[:id])
    @categories=Category.all
  end

  def update
    @item=Item.find(params[:id])
    if @item.update_attributes(item_params)
      redirect_to(item_path(@item, category_id: @category.id))
    else
      @categories=Category.all
      render('edit')
    end
  end

  def delete

  end

  def destroy
    @item=Item.find(params[:id])
    @item.destroy
    redirect_to(items_path(category_id: @category.id))
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :category_id, :description, :image)
  end

  def find_category
    @category=Category.find(params[:category_id])
  end
end

app/controllers/shopfronts_controller.rb
class ShopfrontsController < ApplicationController
  before_action :confirm_logged_in
  def view
    session[:cart_item] ||= []
    @categories=Category.all
    unless params[:q]==nil
      @category=Category.find(params[:q])
      @items=@category.items.all
    else
      @items=Item.all
    end

  end

  def cart
    @user=User.find(session[:email])
    @items=@user.items
    if @items.empty?
      flash[:notice] = "your cart is empty."
      redirect_to(shopfronts_view_path)
    end
  end

  def wishlist
    @user=User.find(session[:email])
    @user.items << Item.find(params[:itm])
    @items=@user.items
    redirect_to(shopfronts_cart_path)
  end

  def usermail
    @user=User.find(session[:email])
    @items=@user.items
    UserMailer.welcome_email(@user,@items).deliver_now
    redirect_to(shopfronts_view_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if session["email"]
      @user=User.find(session[:email])
      if @user.user_type=="admin"
        redirect_to(categories_path)
      else
        redirect_to(shopfronts_view_path)
      end
    else
      @user=User.new
    end
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:email] = @user.id
      flash[:notice] = "you are now logged in."
      user_type=@user.user_type
      if user_type=="admin"
        redirect_to(categories_path)
      else
        redirect_to(shopfronts_view_path)
      end
    else
      render('new')
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :user_type, :contact, :address, :password)
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shopfronts_helper.rb
module ShopfrontsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<% @page_title ="Admin Login" %>
<body>
  <header class="header">
    <span class="container">
      <h2 class="title">Welcome To Jewellery_Plaza</h1>
    </span>
  </header>

  <% if !flash[:notice].blank? %>
    <div class="container notice">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="Categories container">
    <%= form_tag(access_attempt_login_path, method: :post) do %>
    <table class="align">
      <tr>
        <td><%= label_tag(:email) %></td>
        <td class="form-padding"><%= text_field_tag(:email, params[:email]) %></td>
      </tr>
      <tr>
        <td><%= label_tag(:password) %></td>
        <td class="form-padding"><%= password_field_tag(:password) %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td class="form-padding form-buttons"><%= submit_tag("Log In")%></td>
      </tr>
    </table>
    <% end %>
    <%= link_to("Sign Up!!", new_user_path, class: 'action align') %>
  </div>
</body>

app/views/access/shop_front.html.erb
<%= #select_tag 'category_id', options_for_select(@categories.map {|s| [s.name, s.id]}) %>
<%= #button_to 'Call Action', access_shop_front, method: :post %>
<%= form_tag({ controller: 'access', action: 'access_shop_front' }, method: 'get') do %>
  <%= select_tag 'id', options_for_select(@categories.map {|s| [s.name, s.id]}) %>
  <%= submit_tag "Search", name: nil, class: 'btn' %>
<% end %>
<table class="listing" summary="Item list">
  <tr class="header">
    <th>Item_id</th>
    <th>Item_name</th>
    <th>Item_price</th>
    <th>Category_id</th>
    <th>Item_description</th>
    <th>Actions</th>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.price %></td>
    <td><%= item.category_id %></td>
    <td><%= item.description %></td>
  </tr>
  <% end %>

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p> There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
          <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
          <li role="presentation"><%= link_to("<< Back To List",categories_path,class: 'back-link') %></li>
      </ul>
    </div>
  </header>

<div class="Categories edit container">
  <h2> Edit Category</h2>

  <%= form_for(@category) do |f| %>
    <%= error_messages_for(f.object) %>
    <table summary="Category form fields " class="form-group">
      <tr>
        <th>Name:</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Category") %>
    </div>

    <% end %>
  </div>
</body>

app/views/categories/index.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("Add New Category", new_category_path, class: 'action new') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>
  <div class="categories index container">
    <h2>Categories</h2>

    <table class="table table-striped table-inverse" summary="Category list">
      <tr class="">
        <th>Category_id</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td class="actions">
          <%= link_to("Show Items",items_path(category_id: category.id),class: 'action show') %>
          <%= link_to("Edit Category",edit_category_path(category),class: 'action edit') %>
          <%= link_to("Delete Category", category_path(category), method: 'delete', data: {confirm: 'Are you sure you want to delete this category?'}, class: 'action delete') %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</body>

app/views/categories/new.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("<< Back To List",categories_path,class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>
<div class="Categories new container ">
  <h2> Create Category</h2>
  <div >
    <%= form_for(@category) do |f| %>
      <%= error_messages_for(f.object) %>
      <table summary="Category form fields" class="form-group">
        <tr >
          <th>Name:</th>
          <td><%= f.text_field(:name) %></td>
        </tr>
      </table>

      <div class="form-buttons">
        <%= f.submit("Create Category") %>
      </div>

      <% end %>
  </div>
</div>
</body>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/items/delete.html.erb
<h1>Items#delete</h1>
<p>Find me in app/views/items/delete.html.erb</p>

app/views/items/edit.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("<< Back To List",items_path(category_id: @category.id),class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>


<div class="Categories new container">
  <h2> Edit Item</h2>

  <%= form_for(@item, url: item_path(@item, category_id: @category.id)) do |f| %>
    <%= error_messages_for(f.object) %>
    <table summary="Item form fields">
      <tr>
        <th>Name:</th>
        <td class="form-padding"><%= f.text_field(:name) %></td>
      </tr>

      <tr>
        <th>Price:</th>
        <td class="form-padding"><%= f.text_field(:price) %></td>
      </tr>

      <tr>
        <th>Category_name:</th>
        <td class="form-padding"><%= f.select(:category_id, @categories.map {|s| [s.name, s.id]}) %></td>
      </tr>

      <tr>
        <th>Description:</th>
        <td class="form-padding"><%= f.text_area(:description, size: "17*17") %></td>
      </tr>

      <tr>
        <th>Image:</th>
        <td class="form-padding"><%= f.file_field(:image) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Item") %>
    </div>

    <% end %>
  </div>
</body>

app/views/items/index.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("Add New Item", new_item_path(category_id: @category.id), class: 'action new') %></li>
        <li role="presentation"><%= link_to("Back to Categories", categories_path, class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>

  <div class="items index container">
    <h2>Items</h2>

    <table class="listing table table-striped table-inverse" summary="Item list">
      <tr class="">
        <th>Item_id</th>
        <th>Item_name</th>
        <th>Item_price</th>
        <th>Category_id</th>
        <th>Item_description</th>
        <th>Actions</th>
      </tr>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.category_id %></td>
        <td><%= item.description %></td>
        <td class="actions">
          <%= link_to("Show",item_path(item, category_id: @category.id),class: 'action show') %>
          <%= link_to("Edit",edit_item_path(item, category_id: @category.id),class: 'action edit') %>
          <%= link_to("Delete",item_path(item, category_id: @category.id), method: 'delete', data: {confirm: 'Are you sure you want to delete this category?'}, class: 'action delete') %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</body>

app/views/items/new.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("<< Back To List",items_path(category_id: @category.id),class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>

      </ul>
    </div>
  </header>

<div class="Categories new container">
  <h2> Create Item</h2>

  <%= form_for @item, url: items_path(category_id: @category.id), html: { multipart: true } do |f| %>
    <%= error_messages_for(f.object) %>
    <table summary="Item form fields">
      <tr class="form-group">
        <th>Name:</th>
        <td class="form-padding"><%= f.text_field(:name) %></td>
      </tr>

      <tr class="form-group">
        <th>Price:</th>
        <td class="form-padding"><%= f.text_field(:price) %></td>
      </tr>

      <tr class="form-group">
        <th>Category_name:</th>
        <td class="form-padding"><%= f.select(:category_id, @categories.map {|s| [s.name, s.id]}) %></td>
      </tr>

      <tr class="form-group ">
        <th>Description:</th>
        <td class="form-padding"><%= f.text_area(:description, size: "17*17") %></td>
      </tr>

      <tr class="form-group ">
        <th>Image:</th>
        <td class="form-padding"><%= f.file_field(:image) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Item") %>
    </div>

    <% end %>
  </div>
</body>

app/views/items/show.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
          <li role="presentation"><%= link_to("<< Back To List",items_path(category_id: @category.id),class: 'back-link') %></li>
          <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>


  <div class="Categories new container">
    <h2>Show Items</h2>

    <table summary="Item list">
      <tr>
        <th>Item_image:</th>
        <td class="form-padding"><%= image_tag @item.image.url(:medium) %></td>
      </tr>
      <tr>
        <th>Item_id:</th>
        <td class="form-padding"><%= @item.id %></td>
      </tr>
      <tr>
        <th>Item_name:</th>
        <td class="form-padding"><%= @item.name %></td>
      </tr>
      <tr>
        <th>Item_price:</th>
        <td class="form-padding"><%= @item.price %></td>
      </tr>
      <tr>
        <th>Category_name:</th>
        <td class="form-padding"><%= @item.category.name %></td>
      </tr>
      <tr>
        <th>Item_description:</th>
        <td class="form-padding"><%= @item.description %></td>
      </tr>
    </table>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JewelleryStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shopfronts/cart.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("Back To Cart", shopfronts_view_path, class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Mail Wishlist", shopfronts_usermail_path, class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>

  <div class="items index container">
    <h2>Items In Your Wishlist</h2>
    <table class="listing table table-striped table-inverse" summary="Item list">
      <tr class="header">
        <th>Item_image</th>
        <th>Item_name</th>
        <th>Item_price</th>
        <th>Item_description</th>
      </tr>
    <% @items.each do |item| %>
    <tr>
      <td><%= image_tag item.image.url(:thumb) %></td>
      <td><%= item.name %></td>
      <td><%= item.price %></td>
      <td><%= item.description %></td>
    </tr>
    <% end %>
    </table>
</div>
</body>

app/views/shopfronts/view.html.erb
<body>
  <header class="header">
    <div class="container ">
      <ul class="nav nav-pills navbar-right">
        <li role="presentation"><%= link_to("View Wishlist", shopfronts_cart_path, class: 'back-link') %></li>
        <li role="presentation"><%= link_to("Logout", access_logout_path) %></li>
      </ul>
    </div>
  </header>

  <div class="container form-padding">
    <%= form_tag(shopfronts_view_path, method: "get") do %>
      <span class="form-padding text-size"><%= label_tag(:q, "Search for:") %></span>
      <span class="form-padding"><%= select_tag(:q, options_for_select(@categories.map {|s| [s.name, s.id]})) %></span>
      <span class="form-padding"><%= submit_tag("Search") %></span>
    <% end %>
  </div>
  <% if !flash[:notice].blank? %>
    <div class="container notice">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="Categories new container">
    <table class="listing table table-striped table-inverse" summary="Item list">
      <tr class="">
        <th>Item_image</th>
        <th>Item_name</th>
        <th>Item_price</th>
        <th>Item_description</th>
        <th></th>
        <th></th>
      </tr>
    <% @items.each do |item| %>
    <tr>
      <td class="form-padding"><%= image_tag item.image.url(:thumb) %></td>
      <td class="form-padding"><%= item.name %></td>
      <td class="form-padding"><%= item.price %></td>
      <td class="form-padding"><%= item.description %></td>
      <td class="form-padding"><%= link_to "Add to WishList", shopfronts_wishlist_path(itm: item), class: 'back-link' %></td>
      <td class="form-padding"><%= social_share_button_tag(item) %></td>
    </tr>
    <% end %>
    </table>
</div>
</body>

app/views/users/new.html.erb
<body>
  <header class="header">
    <span class="container">
      <h2 class="title">Welcome To Jewellery_Plaza</h1>
    </span>
  </header>

<div class="Categories new container">

  <h1 class="align">Sign up</h1>

  <%= form_for(@user) do |f| %>
    <%= error_messages_for(f.object) %>
    <table summary="User form fields" class="align">
      <tr class="form-group">
        <th>Name:</th>
        <td class="form-padding"><%= f.text_field(:name) %></td>
      </tr>

      <tr class="form-group">
        <th>Email:</th>
        <td class="form-padding"><%= f.email_field(:email) %></td>
      </tr>

      <tr class="form-group">
        <th>User_type:</th>
        <td class="form-padding"><%= f.select(:user_type, ["admin","person"]) %></td>
      </tr>

      <tr class="form-group ">
        <th>Password:</th>
        <td class="form-padding"><%= f.password_field(:password) %></td>
      </tr>

      <tr class="form-group ">
        <th>Contact:</th>
        <td class="form-padding"><%= f.telephone_field(:contact) %></td>
      </tr>

      <tr class="form-group ">
        <th>Address:</th>
        <td class="form-padding"><%= f.text_area(:address, size: "17*17") %></td>
      </tr>
    </table>

    <div class="form-buttons align">
      <%= f.submit("Create User") %>
    </div>

    <% end %>
  </div>
</body>